// @ts-nocheck
/* eslint-disable */

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Return the backend application version (used by the shell to confirm connectivity).
 */
async appVersion() : Promise<string> {
    return await TAURI_INVOKE("app_version");
},
/**
 * Liveness probe exercising the `AppError` contract end-to-end through the bindings.
 */
async ping() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ping") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Inspect local hardware + runtime capabilities (FR-ONB-001, contract §9.1).
 * 
 * Purely local: hardware probing via `sysinfo`, no network access. The app-data volume
 * is used for free-disk reporting so the number reflects where models/indexes will live.
 */
async systemInspect() : Promise<Result<SystemInspection, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("system_inspect") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read settings: one entry when `key` is given, otherwise all entries (contract §9).
 */
async settingsGet(key: string | null) : Promise<Result<SettingEntry[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("settings_get", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write a single setting; `value` is stored as JSON text (contract §9, FR-SET-*).
 */
async settingsSet(key: string, value: JsonValue) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("settings_set", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import a GGUF model file (FR-MOD-001, contract §9.2). Validates, checksums, de-duplicates,
 * and registers the model with a hardware-derived default runtime profile.
 */
async modelsImport(sourcePath: string, storageMode: StorageMode) : Promise<Result<ModelImportResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("models_import", { sourcePath, storageMode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List the model library with per-model compatibility badges (FR-MOD-002, contract §9.2).
 */
async modelsList() : Promise<Result<ModelRow[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("models_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Preflight a model + runtime profile against current memory (FR-ONB-002, contract §9.2).
 */
async modelsEstimateCompatibility(modelId: string, profile: RuntimeProfile) : Promise<Result<CompatibilityAssessment, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("models_estimate_compatibility", { modelId, profile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a model's default runtime profile (backs the FR-MOD-003 editor).
 */
async modelsGetRuntimeProfile(modelId: string) : Promise<Result<RuntimeProfile, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("models_get_runtime_profile", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist edits to a runtime profile (FR-MOD-003, contract §9.2).
 */
async modelsUpdateRuntimeProfile(profile: RuntimeProfile) : Promise<Result<RuntimeProfile, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("models_update_runtime_profile", { profile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Compute a hardware-derived recommended runtime profile (FR-MOD-003 "Reset to Recommended").
 */
async modelsRecommendedRuntimeProfile(modelId: string) : Promise<Result<RuntimeProfile, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("models_recommended_runtime_profile", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a model (FR-MOD-006, contract §9.2). Managed copies are deleted; referenced source
 * files are never touched.
 */
async modelsRemove(modelId: string) : Promise<Result<RemoveResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("models_remove", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * The single error type returned across the command boundary (doc §8.5).
 */
export type AppError = { 
/**
 * Machine-readable classification.
 */
code: AppErrorCode; 
/**
 * Human-readable description of what went wrong.
 */
message: string; 
/**
 * Actionable guidance for how the user can recover.
 */
recovery: string; 
/**
 * Optional structured context; redacted before any export.
 */
details?: Partial<{ [key in string]: JsonValue }> | null }
/**
 * Stable machine-readable error codes (spec §17 / doc §8.5).
 * 
 * Serialized as `SCREAMING_SNAKE_CASE` to match the generated TS discriminated union.
 */
export type AppErrorCode = 
/**
 * Model file is missing, corrupt, or an unsupported format.
 */
"MODEL_INVALID" | 
/**
 * Model could not be loaded because the device is out of memory.
 */
"MODEL_OOM" | 
/**
 * The out-of-process inference runtime crashed or exited unexpectedly.
 */
"RUNTIME_CRASHED" | 
/**
 * The request exceeded the model's context window.
 */
"CONTEXT_EXCEEDED" | 
/**
 * A document could not be parsed (unsupported/corrupt/blocked entity).
 */
"DOCUMENT_PARSE_FAILED" | 
/**
 * A benchmark case exceeded its per-case time budget.
 */
"BENCH_CASE_TIMEOUT" | 
/**
 * A benchmark dataset failed validation.
 */
"DATASET_INVALID" | 
/**
 * Not enough free disk space to complete the operation.
 */
"DISK_SPACE_LOW" | 
/**
 * An unexpected internal error (bug / unhandled condition).
 */
"INTERNAL"
/**
 * Result of a preflight estimate for a model + context length against current hardware.
 */
export type CompatibilityAssessment = { status: CompatibilityStatus; estimatedMemoryBytes: number; 
/**
 * Available memory used for the estimate, or `0` when memory could not be detected.
 */
availableMemoryBytes: number; 
/**
 * Plain-language reasons (never conveyed by color alone, FR-ONB-002).
 */
reasons: string[]; 
/**
 * `true` → the configuration is invalid and loading must be disabled.
 */
blocking: boolean }
/**
 * Three-way compatibility class (contract §8.1).
 */
export type CompatibilityStatus = "recommended" | "may_be_slow" | "not_recommended"
/**
 * A detected GPU (or accelerator). `vram_bytes` is `None` on unified-memory systems.
 */
export type Gpu = { name: string; backend: GpuBackend; vramBytes: number | null }
/**
 * GPU / compute backend family.
 */
export type GpuBackend = "metal" | "cuda" | "vulkan" | "cpu"
/**
 * Local hardware snapshot (contract §8.1). Numeric fields are `None` when undetectable.
 */
export type HardwareInfo = { os: string; arch: string; cpuModel: string | null; logicalCores: number | null; totalMemoryBytes: number | null; availableMemoryBytes: number | null; gpus: Gpu[]; availableDiskBytes: number | null; 
/**
 * Names of fields that could not be detected on this system (FR-ONB-001).
 */
undetected: string[] }
/**
 * `ModelMetadata & { id }` — the import response payload (contract §9.2).
 */
export type ImportedModel = { id: string; format: ModelFormat; architecture: string | null; parameterCount: number | null; quantization: string | null; contextLengthMax: number | null; sizeBytes: number; sha256: string; raw: Partial<{ [key in string]: string }> }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * Model container format. Only GGUF is supported in the MVP (P1: extra formats).
 */
export type ModelFormat = "gguf"
/**
 * Result of `models.import`. `deduplicated` is `true` when the file's checksum already
 * existed in the library — no new copy was made and `model` refers to the existing entry
 * (FR-MOD-001d: "detected and de-duplicated with a prompt").
 */
export type ModelImportResult = { model: ImportedModel; deduplicated: boolean }
/**
 * A library row (FR-MOD-002); returned by `models.list`.
 */
export type ModelRow = { id: string; name: string; fileUri: string; storageMode: StorageMode; sizeBytes: number; sha256: string; architecture: string | null; quantization: string | null; lastUsedAt: string | null; compatibility: CompatibilityAssessment | null }
/**
 * Result of `models.remove` (contract §9.2). `source_file_affected` is `true` only when a
 * file was deleted from disk — which happens for **managed** copies, never for referenced
 * source files (FR-MOD-006).
 */
export type RemoveResult = { ok: boolean; sourceFileAffected: boolean }
/**
 * Capabilities of the active inference runtime (spec §12.2; contract §8.1).
 */
export type RuntimeCapabilities = { engine: RuntimeEngine; 
/**
 * Detected runtime version, or [`ENGINE_VERSION_UNAVAILABLE`] when not installed.
 */
engineVersion: string; supportsSeed: boolean; supportsGpuOffload: boolean; supportsEmbeddings: boolean; deterministicSampling: boolean; 
/**
 * Maximum context the runtime advertises, when known.
 */
maxContext: number | null }
/**
 * Inference engine identifier. Ollama is a post-MVP (P1) adapter.
 */
export type RuntimeEngine = "llama.cpp" | "ollama"
/**
 * A per-model runtime binding (contract §8.1). The generation-sampling fields are packed
 * into `runtime_profiles.generation_defaults_json`; the rest are dedicated columns.
 */
export type RuntimeProfile = { id: string; modelId: string; engine: RuntimeEngine; contextLength: number; maxTokens: number; temperature: number; topP: number; topK: number; repeatPenalty: number; seed: number | null; threads: number; batchSize: number; gpuLayers: number }
/**
 * A single `app_settings` entry exposed to the UI. `value` is the parsed JSON so the
 * frontend receives a real bool/string/number/object rather than a JSON string (§9).
 */
export type SettingEntry = { key: string; value: JsonValue }
/**
 * Where a model's bytes live: referenced in place (default) or copied into app storage.
 */
export type StorageMode = "reference" | "managed"
/**
 * Combined hardware + runtime snapshot returned by `system.inspect` (contract §9.1).
 */
export type SystemInspection = { hardware: HardwareInfo; capabilities: RuntimeCapabilities }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
