// @ts-nocheck
/* eslint-disable */

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Return the backend application version (used by the shell to confirm connectivity).
 */
async appVersion() : Promise<string> {
    return await TAURI_INVOKE("app_version");
},
/**
 * Liveness probe exercising the `AppError` contract end-to-end through the bindings.
 */
async ping() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ping") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * The single error type returned across the command boundary (doc §8.5).
 */
export type AppError = { 
/**
 * Machine-readable classification.
 */
code: AppErrorCode; 
/**
 * Human-readable description of what went wrong.
 */
message: string; 
/**
 * Actionable guidance for how the user can recover.
 */
recovery: string; 
/**
 * Optional structured context; redacted before any export.
 */
details?: Partial<{ [key in string]: JsonValue }> | null }
/**
 * Stable machine-readable error codes (spec §17 / doc §8.5).
 * 
 * Serialized as `SCREAMING_SNAKE_CASE` to match the generated TS discriminated union.
 */
export type AppErrorCode = 
/**
 * Model file is missing, corrupt, or an unsupported format.
 */
"MODEL_INVALID" | 
/**
 * Model could not be loaded because the device is out of memory.
 */
"MODEL_OOM" | 
/**
 * The out-of-process inference runtime crashed or exited unexpectedly.
 */
"RUNTIME_CRASHED" | 
/**
 * The request exceeded the model's context window.
 */
"CONTEXT_EXCEEDED" | 
/**
 * A document could not be parsed (unsupported/corrupt/blocked entity).
 */
"DOCUMENT_PARSE_FAILED" | 
/**
 * A benchmark case exceeded its per-case time budget.
 */
"BENCH_CASE_TIMEOUT" | 
/**
 * A benchmark dataset failed validation.
 */
"DATASET_INVALID" | 
/**
 * Not enough free disk space to complete the operation.
 */
"DISK_SPACE_LOW" | 
/**
 * An unexpected internal error (bug / unhandled condition).
 */
"INTERNAL"
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
